// <auto-generated />
using System;
using Flight.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flight.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20260221080450_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Flight.Models.FlightModel", b =>
                {
                    b.Property<string>("FlightNumber")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FlightNumber");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightNumber = "UA3321",
                            Date = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromCity = "Chicago",
                            Price = 235m,
                            ToCity = "New York"
                        },
                        new
                        {
                            FlightNumber = "QA1078",
                            Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromCity = "Dubai",
                            Price = 590m,
                            ToCity = "London"
                        },
                        new
                        {
                            FlightNumber = "CA9087",
                            Date = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromCity = "Hong Kong",
                            Price = 900m,
                            ToCity = "San Francisco"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
